In [70]:
import pandas as pd
df = pd.read_csv('../data/raw/contratos_menores_2026_csv.csv', sep=';', encoding='latin-1')
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   N. DE REGISTRO DE CONTRATO     974 non-null    int64
 1   N. DE EXPEDIENTE               974 non-null    object
 2   CENTRO - SECCION               974 non-null    object
 3   ORGANO DE CONTRATACION         974 non-null    object
 4   OBJETO DEL CONTRATO            974 non-null    object
 5   TIPO DE CONTRATO               974 non-null    object
 6   N. DE INVITACIONES CURSADAS    967 non-null    float64
 7   INVITADOS A PRESENTAR OFERTA   967 non-null    object
 8   IMPORTE LICITACION IVA INC.    974 non-null    object
 9   N. LICITADORES PARTICIPANTES   974 non-null    int64
 10  NIF ADJUDICATARIO              974 non-null    object
 11  RAZON SOCIAL ADJUDICATARIO     974 non-null    object
 12  PYME                           974 non-null    object
 13  IMPORTE ADJUDICACION IVA INC.  974 non-null    object
 14  FECHA DE ADJUDICACION          974 non-null    object
 15  PLAZO                          974 non-null    object
 16  FECHA DE INSCRIPCION           974 non-null    object
 17  ORGANISMO_CONTRATANTE          974 non-null    object
 18  ORGANISMO_PROMOTOR             974 non-null    object
dtypes: float64(1), int64(2), object(16)
memory usage: 144.7+ KB

In [115]:
pd.read_csv('../data/raw/contratos_menores_2026_csv.csv', sep=';', encoding='latin-1').head()

,N. DE REGISTRO DE CONTRATO,N. DE EXPEDIENTE,CENTRO - SECCION,ORGANO DE CONTRATACION,OBJETO DEL CONTRATO,TIPO DE CONTRATO,N. DE INVITACIONES CURSADAS,INVITADOS A PRESENTAR OFERTA,IMPORTE LICITACION IVA INC.,N. LICITADORES PARTICIPANTES,NIF ADJUDICATARIO,RAZON SOCIAL ADJUDICATARIO,PYME,IMPORTE ADJUDICACION IVA INC.,FECHA DE ADJUDICACION,PLAZO,FECHA DE INSCRIPCION,ORGANISMO_CONTRATANTE,ORGANISMO_PROMOTOR
0,2025015610,511/2025/60303,"VICEALCALDÍA, PORTAVOZ, SEGURID. Y EMERG",DIRECTORA GENERAL DE TRANSPARENCIA Y CALIDAD,Contrato privado para la suscripción a la plat...,Servicios,1.0,"(B85893493) AENOR CONOCIMIENTO, S.L.U.. PYME: N0","15.808,00",1,B85893493,"AENOR CONOCIMIENTO, S.L.U.",NO,"15.808,00",23/12/25,"12,00",02/01/26,"ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE...","ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE..."
1,2025015611,CM25/00076/2,Empresa Municipal de Transportes E.M.T.,DIRECTOR/A GERENTE,"SUMINISTRO DE 103 CHUBASQUEROS, ESPECIALMENTE ...",Suministros,1.0,(03108110M) SUSANA SANCHEZ MARTÍN. PYME: SI,"3.601,81",1,03108110M,SUSANA SANCHEZ MARTÍN,SI,"3.601,81",23/12/25,"3,00",05/01/26,EMPRESA MUNICIPAL DE TRANSPORTES,EMPRESA MUNICIPAL DE TRANSPORTES
2,2025015653,MER/2025/00468,MercaMadrid,DIRECTOR/A GENERAL,SERVICIOS DE AUDITORÍA EXTERNA DE CERTIFICACIÓ...,Servicios,1.0,"(B66084591) ICQD INSTITUTO DE CERTIFICACIÓN, S...","514,25",1,B66084591,"ICQD INSTITUTO DE CERTIFICACIÓN, S.L.",SI,"514,25",07/11/25,"6,00",05/01/26,MERCAMADRID,MERCAMADRID
3,2025015655,MER/2025/00442,MercaMadrid,DIRECTOR/A GENERAL,SUMINISTRO DE CABLE FLEXIBLE DE TENSIÓN,Suministros,1.0,(B83128942) ONELEC SUMINISTROS ELECTRICOS S.L....,"1.452,00",1,B83128942,ONELEC SUMINISTROS ELECTRICOS S.L.,SI,"1.432,64",07/11/25,"0,23",05/01/26,MERCAMADRID,MERCAMADRID
4,2025015659,PR25-0314.1,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",GERENTE DE MATADERO,PR25-0314.1 CONTRATO MENOR DEL SERVICIO DE DI...,Servicios,1.0,(02549159T) Maria Teresa Blasco Marin-Borregon...,"2.420,00",1,02549159T,Maria Teresa Blasco Marin-Borregon,NO,"2.420,00",17/12/25,"7,40",07/01/26,MADRID DESTINO,MADRID DESTINO

In [114]:
df.head(2)

,N_DE_REGISTRO_DE_CONTRATO,N_DE_EXPEDIENTE,CENTRO_SECCION,ORGANO_DE_CONTRATACION,OBJETO_DEL_CONTRATO,TIPO_DE_CONTRATO,N_DE_INVITACIONES_CURSADAS,INVITADOS_A_PRESENTAR_OFERTA,IMPORTE_LICITACION_IVA_INC,N_LICITADORES_PARTICIPANTES,NIF_ADJUDICATARIO,RAZON_SOCIAL_ADJUDICATARIO,PYME,IMPORTE_ADJUDICACION_IVA_INC,FECHA_DE_ADJUDICACION,PLAZO,FECHA_DE_INSCRIPCION,ORGANISMO_CONTRATANTE,ORGANISMO_PROMOTOR,MES
0,2025015610,511/2025/60303,"VICEALCALDÍA, PORTAVOZ, SEGURID. Y EMERG",DIRECTORA GENERAL DE TRANSPARENCIA Y CALIDAD,Contrato privado para la suscripción a la plat...,SERVICIOS,1,"(B85893493) AENOR CONOCIMIENTO, S.L.U.. PYME: N0",15808.00,1,B85893493,"AENOR CONOCIMIENTO, S.L.U.",NO,15808.00,2025-12-23,12.0,2026-01-02,"ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE...","ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE...",2025-12
1,2025015611,CM25/00076/2,EMPRESA MUNICIPAL DE TRANSPORTES E.M.T.,DIRECTOR/A GERENTE,"SUMINISTRO DE 103 CHUBASQUEROS, ESPECIALMENTE ...",SUMINISTROS,1,(03108110M) SUSANA SANCHEZ MARTÍN. PYME: SI,3601.81,1,03108110M,SUSANA SANCHEZ MARTÍN,SI,3601.81,2025-12-23,3.0,2026-01-05,EMPRESA MUNICIPAL DE TRANSPORTES,EMPRESA MUNICIPAL DE TRANSPORTES,2025-12

In [71]:
df.columns = (
    df.columns
    .str.strip()
    .str.upper()
    .str.replace(' - ', '_', regex=False)    
    .str.replace(' ', '_')
    .str.replace('.', '', regex=False)
)
df

,N_DE_REGISTRO_DE_CONTRATO,N_DE_EXPEDIENTE,CENTRO_SECCION,ORGANO_DE_CONTRATACION,OBJETO_DEL_CONTRATO,TIPO_DE_CONTRATO,N_DE_INVITACIONES_CURSADAS,INVITADOS_A_PRESENTAR_OFERTA,IMPORTE_LICITACION_IVA_INC,N_LICITADORES_PARTICIPANTES,NIF_ADJUDICATARIO,RAZON_SOCIAL_ADJUDICATARIO,PYME,IMPORTE_ADJUDICACION_IVA_INC,FECHA_DE_ADJUDICACION,PLAZO,FECHA_DE_INSCRIPCION,ORGANISMO_CONTRATANTE,ORGANISMO_PROMOTOR
0,2025015610,511/2025/60303,"VICEALCALDÍA, PORTAVOZ, SEGURID. Y EMERG",DIRECTORA GENERAL DE TRANSPARENCIA Y CALIDAD,Contrato privado para la suscripción a la plat...,Servicios,1.0,"(B85893493) AENOR CONOCIMIENTO, S.L.U.. PYME: N0","15.808,00",1,B85893493,"AENOR CONOCIMIENTO, S.L.U.",NO,"15.808,00",23/12/25,"12,00",02/01/26,"ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE...","ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE..."
1,2025015611,CM25/00076/2,Empresa Municipal de Transportes E.M.T.,DIRECTOR/A GERENTE,"SUMINISTRO DE 103 CHUBASQUEROS, ESPECIALMENTE ...",Suministros,1.0,(03108110M) SUSANA SANCHEZ MARTÍN. PYME: SI,"3.601,81",1,03108110M,SUSANA SANCHEZ MARTÍN,SI,"3.601,81",23/12/25,"3,00",05/01/26,EMPRESA MUNICIPAL DE TRANSPORTES,EMPRESA MUNICIPAL DE TRANSPORTES
2,2025015653,MER/2025/00468,MercaMadrid,DIRECTOR/A GENERAL,SERVICIOS DE AUDITORÍA EXTERNA DE CERTIFICACIÓ...,Servicios,1.0,"(B66084591) ICQD INSTITUTO DE CERTIFICACIÓN, S...","514,25",1,B66084591,"ICQD INSTITUTO DE CERTIFICACIÓN, S.L.",SI,"514,25",07/11/25,"6,00",05/01/26,MERCAMADRID,MERCAMADRID
3,2025015655,MER/2025/00442,MercaMadrid,DIRECTOR/A GENERAL,SUMINISTRO DE CABLE FLEXIBLE DE TENSIÓN,Suministros,1.0,(B83128942) ONELEC SUMINISTROS ELECTRICOS S.L....,"1.452,00",1,B83128942,ONELEC SUMINISTROS ELECTRICOS S.L.,SI,"1.432,64",07/11/25,"0,23",05/01/26,MERCAMADRID,MERCAMADRID
4,2025015659,PR25-0314.1,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",GERENTE DE MATADERO,PR25-0314.1 CONTRATO MENOR DEL SERVICIO DE DI...,Servicios,1.0,(02549159T) Maria Teresa Blasco Marin-Borregon...,"2.420,00",1,02549159T,Maria Teresa Blasco Marin-Borregon,NO,"2.420,00",17/12/25,"7,40",07/01/26,MADRID DESTINO,MADRID DESTINO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,2026003056,120/2026/00493,DISTRITO DE VILLA DE VALLECAS,COORDINADOR DEL DISTRITO DE VILLA DE VALLECAS,INTERPRETACIÓN DE ESPECTÁCULO MUSICAL EN LA EX...,Servicios,1.0,"(B85705945) UNK INNOVACIÓN Y TELECOMUNICACIÓN,...","11.495,00",1,B85705945,"UNK INNOVACIÓN Y TELECOMUNICACIÓN, S.L.",SI,"11.495,00",25/03/26,"0,03",31/03/26,DISTRITO DE VILLA DE VALLECAS,DISTRITO DE VILLA DE VALLECAS
970,2026003057,107/2026/00709,DISTRITO DE CHAMBERÍ,COORDINADOR DEL DISTRITO DE CHAMBERÍ,CONTRATO MENOR PRIVADO PARA LA CONTRATACION DE...,Servicios,1.0,(G09840166) ASOCIACIÓN MUSICAL CANTA ET AMBULA...,"6.000,00",1,G09840166,ASOCIACIÓN MUSICAL CANTA ET AMBULA,SI,"6.000,00",18/03/26,"0,03",31/03/26,DISTRITO DE CHAMBERÍ,DISTRITO DE CHAMBERÍ
971,2026003064,300/2026/00874,COORDINACIÓN GENERAL DE LA ALCALDÍA,SECRETARIA GENERAL TÉCNICA DE LA COORDINACIÓN ...,Compra de placas de protección para suelos.,Suministros,1.0,(B88331475) DISTRIBUCIONES FIGUREX MADRID SL. ...,"1.710,58",1,B88331475,DISTRIBUCIONES FIGUREX MADRID SL,SI,"1.710,58",30/03/26,"1,00",31/03/26,COORDINACIÓN GENERAL DE LA ALCALDÍA,COORDINACIÓN GENERAL DE LA ALCALDÍA
972,2026003067,300/2026/00758,AGENCIA PARA EL EMPLEO DE MADRID,GERENTE AGENCIA PARA EL EMPLEO,Contrato menor de servicio de modificación y a...,Servicios,1.0,(B86580354) Cosmika Producciones Audiovisuales...,"3.599,75",1,B86580354,Cosmika Producciones Audiovisuales SL,SI,"3.599,75",31/03/26,"8,50",31/03/26,OOAA AGENCIA PARA EL EMPLEO DE MADRID,OOAA AGENCIA PARA EL EMPLEO DE MADRID
973,2026003069,300/2026/00748,"URBANISMO, MEDIO AMBIENTE Y MOVILIDAD",DIRECTORA GENERAL DE PLANIFICACIÓN ESTRATÉGICA,Redacción de un estudio de puesta en valor de ...,Servicios,3.0,(02523611M) ANTONIO SAMA GARCÍA. PYME: N0\n(05...,"18.125,80",3,Q2818016D,UNIVERSIDAD NACIONAL DE EDUCACIÓN A DISTANCIA,NO,"17.908,00",30/03/26,"8,00",31/03/26,"ÁREA DE GOBIERNO DE URBANISMO, MEDIO AMBIENTE ...","ÁREA DE GOBIERNO DE URBANISMO, MEDIO AMBIENTE ..."

In [72]:
cols_importe = ['IMPORTE_LICITACION_IVA_INC', 'IMPORTE_ADJUDICACION_IVA_INC']  # columnas de dinero

for col in cols_importe:                                                        # recorre cada columna de importe
    df[col] = (                                                                 # sobrescribe la columna ya limpia
        df[col].astype(str)                                                     # asegura texto
        .str.replace(r'[^\d,.-]', '', regex=True)                               # elimina símbolos raros como € o 
        .str.replace('.', '', regex=False)                                      # quita separador de miles
        .str.replace(',', '.', regex=False)                                     # convierte coma decimal a punto
        .pipe(pd.to_numeric, errors='coerce')                                   # convierte a número
    )

In [73]:
df

,N_DE_REGISTRO_DE_CONTRATO,N_DE_EXPEDIENTE,CENTRO_SECCION,ORGANO_DE_CONTRATACION,OBJETO_DEL_CONTRATO,TIPO_DE_CONTRATO,N_DE_INVITACIONES_CURSADAS,INVITADOS_A_PRESENTAR_OFERTA,IMPORTE_LICITACION_IVA_INC,N_LICITADORES_PARTICIPANTES,NIF_ADJUDICATARIO,RAZON_SOCIAL_ADJUDICATARIO,PYME,IMPORTE_ADJUDICACION_IVA_INC,FECHA_DE_ADJUDICACION,PLAZO,FECHA_DE_INSCRIPCION,ORGANISMO_CONTRATANTE,ORGANISMO_PROMOTOR
0,2025015610,511/2025/60303,"VICEALCALDÍA, PORTAVOZ, SEGURID. Y EMERG",DIRECTORA GENERAL DE TRANSPARENCIA Y CALIDAD,Contrato privado para la suscripción a la plat...,Servicios,1.0,"(B85893493) AENOR CONOCIMIENTO, S.L.U.. PYME: N0",15808.00,1,B85893493,"AENOR CONOCIMIENTO, S.L.U.",NO,15808.00,23/12/25,"12,00",02/01/26,"ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE...","ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE..."
1,2025015611,CM25/00076/2,Empresa Municipal de Transportes E.M.T.,DIRECTOR/A GERENTE,"SUMINISTRO DE 103 CHUBASQUEROS, ESPECIALMENTE ...",Suministros,1.0,(03108110M) SUSANA SANCHEZ MARTÍN. PYME: SI,3601.81,1,03108110M,SUSANA SANCHEZ MARTÍN,SI,3601.81,23/12/25,"3,00",05/01/26,EMPRESA MUNICIPAL DE TRANSPORTES,EMPRESA MUNICIPAL DE TRANSPORTES
2,2025015653,MER/2025/00468,MercaMadrid,DIRECTOR/A GENERAL,SERVICIOS DE AUDITORÍA EXTERNA DE CERTIFICACIÓ...,Servicios,1.0,"(B66084591) ICQD INSTITUTO DE CERTIFICACIÓN, S...",514.25,1,B66084591,"ICQD INSTITUTO DE CERTIFICACIÓN, S.L.",SI,514.25,07/11/25,"6,00",05/01/26,MERCAMADRID,MERCAMADRID
3,2025015655,MER/2025/00442,MercaMadrid,DIRECTOR/A GENERAL,SUMINISTRO DE CABLE FLEXIBLE DE TENSIÓN,Suministros,1.0,(B83128942) ONELEC SUMINISTROS ELECTRICOS S.L....,1452.00,1,B83128942,ONELEC SUMINISTROS ELECTRICOS S.L.,SI,1432.64,07/11/25,"0,23",05/01/26,MERCAMADRID,MERCAMADRID
4,2025015659,PR25-0314.1,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",GERENTE DE MATADERO,PR25-0314.1 CONTRATO MENOR DEL SERVICIO DE DI...,Servicios,1.0,(02549159T) Maria Teresa Blasco Marin-Borregon...,2420.00,1,02549159T,Maria Teresa Blasco Marin-Borregon,NO,2420.00,17/12/25,"7,40",07/01/26,MADRID DESTINO,MADRID DESTINO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,2026003056,120/2026/00493,DISTRITO DE VILLA DE VALLECAS,COORDINADOR DEL DISTRITO DE VILLA DE VALLECAS,INTERPRETACIÓN DE ESPECTÁCULO MUSICAL EN LA EX...,Servicios,1.0,"(B85705945) UNK INNOVACIÓN Y TELECOMUNICACIÓN,...",11495.00,1,B85705945,"UNK INNOVACIÓN Y TELECOMUNICACIÓN, S.L.",SI,11495.00,25/03/26,"0,03",31/03/26,DISTRITO DE VILLA DE VALLECAS,DISTRITO DE VILLA DE VALLECAS
970,2026003057,107/2026/00709,DISTRITO DE CHAMBERÍ,COORDINADOR DEL DISTRITO DE CHAMBERÍ,CONTRATO MENOR PRIVADO PARA LA CONTRATACION DE...,Servicios,1.0,(G09840166) ASOCIACIÓN MUSICAL CANTA ET AMBULA...,6000.00,1,G09840166,ASOCIACIÓN MUSICAL CANTA ET AMBULA,SI,6000.00,18/03/26,"0,03",31/03/26,DISTRITO DE CHAMBERÍ,DISTRITO DE CHAMBERÍ
971,2026003064,300/2026/00874,COORDINACIÓN GENERAL DE LA ALCALDÍA,SECRETARIA GENERAL TÉCNICA DE LA COORDINACIÓN ...,Compra de placas de protección para suelos.,Suministros,1.0,(B88331475) DISTRIBUCIONES FIGUREX MADRID SL. ...,1710.58,1,B88331475,DISTRIBUCIONES FIGUREX MADRID SL,SI,1710.58,30/03/26,"1,00",31/03/26,COORDINACIÓN GENERAL DE LA ALCALDÍA,COORDINACIÓN GENERAL DE LA ALCALDÍA
972,2026003067,300/2026/00758,AGENCIA PARA EL EMPLEO DE MADRID,GERENTE AGENCIA PARA EL EMPLEO,Contrato menor de servicio de modificación y a...,Servicios,1.0,(B86580354) Cosmika Producciones Audiovisuales...,3599.75,1,B86580354,Cosmika Producciones Audiovisuales SL,SI,3599.75,31/03/26,"8,50",31/03/26,OOAA AGENCIA PARA EL EMPLEO DE MADRID,OOAA AGENCIA PARA EL EMPLEO DE MADRID
973,2026003069,300/2026/00748,"URBANISMO, MEDIO AMBIENTE Y MOVILIDAD",DIRECTORA GENERAL DE PLANIFICACIÓN ESTRATÉGICA,Redacción de un estudio de puesta en valor de ...,Servicios,3.0,(02523611M) ANTONIO SAMA GARCÍA. PYME: N0\n(05...,18125.80,3,Q2818016D,UNIVERSIDAD NACIONAL DE EDUCACIÓN A DISTANCIA,NO,17908.00,30/03/26,"8,00",31/03/26,"ÁREA DE GOBIERNO DE URBANISMO, MEDIO AMBIENTE ...","ÁREA DE GOBIERNO DE URBANISMO, MEDIO AMBIENTE ..."

In [82]:
df[['IMPORTE_ADJUDICACION_IVA_INC', 'IMPORTE_LICITACION_IVA_INC']].info()  # verificar tipo float

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 2 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   IMPORTE_ADJUDICACION_IVA_INC  974 non-null    float64
 1   IMPORTE_LICITACION_IVA_INC    974 non-null    float64
dtypes: float64(2)
memory usage: 15.3 KB

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   N_DE_REGISTRO_DE_CONTRATO     974 non-null    int64
 1   N_DE_EXPEDIENTE               974 non-null    object
 2   CENTRO_SECCION                974 non-null    object
 3   ORGANO_DE_CONTRATACION        974 non-null    object
 4   OBJETO_DEL_CONTRATO           974 non-null    object
 5   TIPO_DE_CONTRATO              974 non-null    object
 6   N_DE_INVITACIONES_CURSADAS    967 non-null    float64
 7   INVITADOS_A_PRESENTAR_OFERTA  967 non-null    object
 8   IMPORTE_LICITACION_IVA_INC    974 non-null    float64
 9   N_LICITADORES_PARTICIPANTES   974 non-null    int64
 10  NIF_ADJUDICATARIO             974 non-null    object
 11  RAZON_SOCIAL_ADJUDICATARIO    974 non-null    object
 12  PYME                          974 non-null    object
 13  IMPORTE_ADJUDICACION_IVA_INC  974 non-null    float64
 14  FECHA_DE_ADJUDICACION         974 non-null    object
 15  PLAZO                         974 non-null    float64
 16  FECHA_DE_INSCRIPCION          974 non-null    object
 17  ORGANISMO_CONTRATANTE         974 non-null    object
 18  ORGANISMO_PROMOTOR            974 non-null    object
dtypes: float64(4), int64(2), object(13)
memory usage: 144.7+ KB

In [84]:
df[['IMPORTE_ADJUDICACION_IVA_INC', 'IMPORTE_LICITACION_IVA_INC']].isna().sum()  # revisar NaN

IMPORTE_ADJUDICACION_IVA_INC    0
IMPORTE_LICITACION_IVA_INC      0
dtype: int64

In [85]:
df[['IMPORTE_ADJUDICACION_IVA_INC', 'IMPORTE_LICITACION_IVA_INC']].describe()

       IMPORTE_ADJUDICACION_IVA_INC  IMPORTE_LICITACION_IVA_INC
count                    974.000000                  974.000000
mean                    7013.965441                 7477.122177
std                     9520.325451                 9746.077363
min                       29.040000                   30.250000
25%                     2082.712500                 2264.977500
50%                     3971.220000                 4235.000000
75%                    11090.257500                11994.750000
max                   231251.570000               231251.570000

In [86]:
num_cols = df.select_dtypes(include=['int64','float64']).columns      # numéricas
obj_cols = df.select_dtypes(include=['object']).columns               # texto
num_cols, obj_cols

(Index(['N_DE_REGISTRO_DE_CONTRATO', 'N_DE_INVITACIONES_CURSADAS',
        'IMPORTE_LICITACION_IVA_INC', 'N_LICITADORES_PARTICIPANTES',
        'IMPORTE_ADJUDICACION_IVA_INC', 'PLAZO'],
       dtype='object'),
 Index(['N_DE_EXPEDIENTE', 'CENTRO_SECCION', 'ORGANO_DE_CONTRATACION',
        'OBJETO_DEL_CONTRATO', 'TIPO_DE_CONTRATO',
        'INVITADOS_A_PRESENTAR_OFERTA', 'NIF_ADJUDICATARIO',
        'RAZON_SOCIAL_ADJUDICATARIO', 'PYME', 'FECHA_DE_ADJUDICACION',
        'FECHA_DE_INSCRIPCION', 'ORGANISMO_CONTRATANTE', 'ORGANISMO_PROMOTOR'],
       dtype='object'))

In [87]:
df['PLAZO'] = (
    df['PLAZO'].astype(str)
    .str.replace(',', '.', regex=False)
    .pipe(pd.to_numeric, errors='coerce')
)

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   N_DE_REGISTRO_DE_CONTRATO     974 non-null    int64
 1   N_DE_EXPEDIENTE               974 non-null    object
 2   CENTRO_SECCION                974 non-null    object
 3   ORGANO_DE_CONTRATACION        974 non-null    object
 4   OBJETO_DEL_CONTRATO           974 non-null    object
 5   TIPO_DE_CONTRATO              974 non-null    object
 6   N_DE_INVITACIONES_CURSADAS    967 non-null    float64
 7   INVITADOS_A_PRESENTAR_OFERTA  967 non-null    object
 8   IMPORTE_LICITACION_IVA_INC    974 non-null    float64
 9   N_LICITADORES_PARTICIPANTES   974 non-null    int64
 10  NIF_ADJUDICATARIO             974 non-null    object
 11  RAZON_SOCIAL_ADJUDICATARIO    974 non-null    object
 12  PYME                          974 non-null    object
 13  IMPORTE_ADJUDICACION_IVA_INC  974 non-null    float64
 14  FECHA_DE_ADJUDICACION         974 non-null    object
 15  PLAZO                         974 non-null    float64
 16  FECHA_DE_INSCRIPCION          974 non-null    object
 17  ORGANISMO_CONTRATANTE         974 non-null    object
 18  ORGANISMO_PROMOTOR            974 non-null    object
dtypes: float64(4), int64(2), object(13)
memory usage: 144.7+ KB

In [89]:
df.head(20)

,N_DE_REGISTRO_DE_CONTRATO,N_DE_EXPEDIENTE,CENTRO_SECCION,ORGANO_DE_CONTRATACION,OBJETO_DEL_CONTRATO,TIPO_DE_CONTRATO,N_DE_INVITACIONES_CURSADAS,INVITADOS_A_PRESENTAR_OFERTA,IMPORTE_LICITACION_IVA_INC,N_LICITADORES_PARTICIPANTES,NIF_ADJUDICATARIO,RAZON_SOCIAL_ADJUDICATARIO,PYME,IMPORTE_ADJUDICACION_IVA_INC,FECHA_DE_ADJUDICACION,PLAZO,FECHA_DE_INSCRIPCION,ORGANISMO_CONTRATANTE,ORGANISMO_PROMOTOR
0,2025015610,511/2025/60303,"VICEALCALDÍA, PORTAVOZ, SEGURID. Y EMERG",DIRECTORA GENERAL DE TRANSPARENCIA Y CALIDAD,Contrato privado para la suscripción a la plat...,Servicios,1.0,"(B85893493) AENOR CONOCIMIENTO, S.L.U.. PYME: N0",15808.00,1,B85893493,"AENOR CONOCIMIENTO, S.L.U.",NO,15808.00,23/12/25,12.00,02/01/26,"ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE...","ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE..."
1,2025015611,CM25/00076/2,Empresa Municipal de Transportes E.M.T.,DIRECTOR/A GERENTE,"SUMINISTRO DE 103 CHUBASQUEROS, ESPECIALMENTE ...",Suministros,1.0,(03108110M) SUSANA SANCHEZ MARTÍN. PYME: SI,3601.81,1,03108110M,SUSANA SANCHEZ MARTÍN,SI,3601.81,23/12/25,3.00,05/01/26,EMPRESA MUNICIPAL DE TRANSPORTES,EMPRESA MUNICIPAL DE TRANSPORTES
2,2025015653,MER/2025/00468,MercaMadrid,DIRECTOR/A GENERAL,SERVICIOS DE AUDITORÍA EXTERNA DE CERTIFICACIÓ...,Servicios,1.0,"(B66084591) ICQD INSTITUTO DE CERTIFICACIÓN, S...",514.25,1,B66084591,"ICQD INSTITUTO DE CERTIFICACIÓN, S.L.",SI,514.25,07/11/25,6.00,05/01/26,MERCAMADRID,MERCAMADRID
3,2025015655,MER/2025/00442,MercaMadrid,DIRECTOR/A GENERAL,SUMINISTRO DE CABLE FLEXIBLE DE TENSIÓN,Suministros,1.0,(B83128942) ONELEC SUMINISTROS ELECTRICOS S.L....,1452.00,1,B83128942,ONELEC SUMINISTROS ELECTRICOS S.L.,SI,1432.64,07/11/25,0.23,05/01/26,MERCAMADRID,MERCAMADRID
4,2025015659,PR25-0314.1,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",GERENTE DE MATADERO,PR25-0314.1 CONTRATO MENOR DEL SERVICIO DE DI...,Servicios,1.0,(02549159T) Maria Teresa Blasco Marin-Borregon...,2420.00,1,02549159T,Maria Teresa Blasco Marin-Borregon,NO,2420.00,17/12/25,7.40,07/01/26,MADRID DESTINO,MADRID DESTINO
5,2025015660,PR25-0191.2,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",GERENTE DEL CENTRO DANZA MATADERO,PR25-0191.2 CONTRATO MENOR DE SUMINISTRO DE MA...,Suministros,3.0,(B33577578) ASTURMEDIA S. L.. PYME: SI\n(B3965...,2178.00,2,B33577578,ASTURMEDIA S. L.,SI,2081.20,10/12/25,0.40,07/01/26,MADRID DESTINO,MADRID DESTINO
6,2025015661,PR25-0219.5,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",GERENTE DE TEATRO CIRCO PRICE,PR25-0219.5 CONTRATO MENOR DE COMPRA DE MESA P...,Suministros,1.0,"(B86016284) SISTEMAS Y SERVICIOS AUDIO, S.L.. ...",3091.55,1,B86016284,"SISTEMAS Y SERVICIOS AUDIO, S.L.",SI,3091.55,22/12/25,0.30,07/01/26,MADRID DESTINO,MADRID DESTINO
7,2025015684,300/2025/04053,POLÍTICAS DE VIVIENDA,SECRETARIA GENERAL TÉCNICA DE POLÍTICAS DE VIV...,Contrato menor de servicios de mantenimiento d...,Servicios,1.0,"(A79486833) ELECNOR SERVICIOS Y PROYECTOS, S.A...",6655.00,1,A79486833,"ELECNOR SERVICIOS Y PROYECTOS, S.A.U.",NO,6655.00,26/12/25,1.00,08/01/26,ÁREA DE GOBIERNO DE POLÍTICAS DE VIVIENDA,ÁREA DE GOBIERNO DE POLÍTICAS DE VIVIENDA
8,2025015724,SP25-00566,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",DIRECTOR/A DE COMUNICACIÓN,CONTRATO MENOR DEL SERVICIO DE ILUSTRACION PAR...,Servicios,1.0,(07221839T) IGNACIO SEVILLA HIDALGO. PYME: N0,3000.00,1,07221839T,IGNACIO SEVILLA HIDALGO,NO,3000.00,20/11/25,12.00,08/01/26,MADRID DESTINO,MADRID DESTINO
9,2025015725,SP25-00599,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",DIRECTOR/A DE COMUNICACIÓN,CONTRATO MENOR PARA EL SERVICIO DE ILUSTRACION...,Servicios,1.0,(50211244J) EDUARDO BARBA. PYME: N0,1500.00,1,50211244J,EDUARDO BARBA,NO,1500.00,03/12/25,12.00,08/01/26,MADRID DESTINO,MADRID DESTINO
10,2025015726,SP25-00607,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",DIRECTOR/A DE COMUNICACIÓN,CONTRATO MENOR POR EL SERVICIO DE ILUSTRACION ...,Servicios,1.0,(46858146Q) RAUL TORRES GUZMAN. PYME: N0,3000.00,1,46858146Q,RAUL TORRES GUZMAN,NO,3000.00,16/12/25,12.00,08/01/26,MADRID DESTINO,MADRID DESTINO
11,2025015727,SP25-00586,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",DIRECTOR/A DE COMUNICACIÓN,GASTO MENOR SERVICIOS DE GRABACION Y FOTOGRAFÍ...,Servicios,3.0,(B06875223) Beon Studio S.L.. PYME: N0\n(B5618...,14144.90,2,B72924491,POLVORA PRODUCCIONES S.L.,SI,14144.90,12/12/25,1.26,08/01/26,MADRID DESTINO,MADRID DESTINO
12,2025015728,SP25-00598,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",DIRECTOR/A DE COMUNICACIÓN,SP25-00598 CONTRATO MENOR DEL SERVICIO CATERI...,Servicios,1.0,(B85855385) ISABEL CASTAÑAR SANCHEZ S.L. PYME: SI,3630.00,1,B85855385,ISABEL CASTAÑAR SANCHEZ S.L,SI,2810.00,20/11/25,0.30,08/01/26,MADRID DESTINO,MADRID DESTINO
13,2025015756,300/2025/04120,DISTRITO DE LATINA,COORDINADOR DEL DISTRITO DE LATINA,Contrato menor de servicios para la implementa...,Servicios,3.0,"(B59416479) HARTFORD, S.L.. PYME: N0\n(G289791...",6140.20,1,B59416479,"HARTFORD, S.L.",NO,5900.42,30/12/25,2.60,09/01/26,DISTRITO DE LATINA,DISTRITO DE LATINA
14,2025015812,PR25-0328.1,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",GERENTE DE CENTROCENTRO,"GASTO MENOR DE CONTRATO MENOR DE PRODUCCIÓN, P...",Servicios,1.0,(50718986F) Illán Gonzalo Argüello Pascual. PY...,2904.00,1,50718986F,Illán Gonzalo Argüello Pascual,NO,2640.00,29/12/25,2.00,13/01/26,MADRID DESTINO,MADRID DESTINO
15,2025015814,PR25-0230.01,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",GERENTE DE CONDE DUQUE,PR25-0230.01 CONTRATO MENOR PARA LA REPRESENTA...,Servicios,1.0,(RUT651972957) Fundación Cuerpo Sur. PYME: N0,8815.78,1,RUT651972957,Fundación Cuerpo Sur,NO,8815.78,25/09/25,0.10,13/01/26,MADRID DESTINO,MADRID DESTINO
16,2025015815,PR25-0263.1,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",GERENTE DE CONDE DUQUE,PR25-0263.1 CONTRATO MENOR PARA LA CONTRATACIO...,Servicios,1.0,(N13621281) José Ricardo Gallardo Ortega. PYME...,13157.89,1,N13621281,José Ricardo Gallardo Ortega,NO,13157.89,05/12/25,0.06,13/01/26,MADRID DESTINO,MADRID DESTINO
17,2025015817,PR25-0249.1,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",GERENTE DE CONDE DUQUE,PR25-0249.1 CONTRATO MENOR DE ALQUILER DE MATE...,Suministros,1.0,(B82601493) EVILUX S.L.. PYME: SI,1185.80,1,B82601493,EVILUX S.L.,SI,1185.80,16/12/25,0.60,13/01/26,MADRID DESTINO,MADRID DESTINO
18,2025015818,PR25-0299.1,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",GERENTE DE CONDE DUQUE,PR25-0299.1 CONTRATO MENOR PARA LA CONTRATACI...,Servicios,1.0,(G85605624) Paso a 2 Plataforma Coreográfica A...,3630.00,1,G85605624,Paso a 2 Plataforma Coreográfica Asociación Cu...,NO,3630.00,20/11/25,0.13,13/01/26,MADRID DESTINO,MADRID DESTINO
19,2025015819,PR25-0224.2,"Madrid Destino, Cultura, Turismo y Negocio, S.A.",GERENTE DE CONDE DUQUE,"PR25-0224.2 CONTRATO MENOR DE SUMINISTRO, EN R...",Suministros,1.0,"(B09356551) SPIKA SONIDO E ILUMINACIÓN, S.L.U....",992.20,1,B09356551,"SPIKA SONIDO E ILUMINACIÓN, S.L.U",SI,992.20,05/12/25,0.13,13/01/26,MADRID DESTINO,MADRID DESTINO

In [90]:
columns = ['N_LICITADORES_PARTICIPANTES', 'N_DE_INVITACIONES_CURSADAS']
df[columns] = df[columns].apply(pd.to_numeric, errors='coerce').astype('Int64')

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   N_DE_REGISTRO_DE_CONTRATO     974 non-null    int64
 1   N_DE_EXPEDIENTE               974 non-null    object
 2   CENTRO_SECCION                974 non-null    object
 3   ORGANO_DE_CONTRATACION        974 non-null    object
 4   OBJETO_DEL_CONTRATO           974 non-null    object
 5   TIPO_DE_CONTRATO              974 non-null    object
 6   N_DE_INVITACIONES_CURSADAS    967 non-null    Int64
 7   INVITADOS_A_PRESENTAR_OFERTA  967 non-null    object
 8   IMPORTE_LICITACION_IVA_INC    974 non-null    float64
 9   N_LICITADORES_PARTICIPANTES   974 non-null    Int64
 10  NIF_ADJUDICATARIO             974 non-null    object
 11  RAZON_SOCIAL_ADJUDICATARIO    974 non-null    object
 12  PYME                          974 non-null    object
 13  IMPORTE_ADJUDICACION_IVA_INC  974 non-null    float64
 14  FECHA_DE_ADJUDICACION         974 non-null    object
 15  PLAZO                         974 non-null    float64
 16  FECHA_DE_INSCRIPCION          974 non-null    object
 17  ORGANISMO_CONTRATANTE         974 non-null    object
 18  ORGANISMO_PROMOTOR            974 non-null    object
dtypes: Int64(2), float64(3), int64(1), object(13)
memory usage: 146.6+ KB

In [92]:
df[['N_LICITADORES_PARTICIPANTES', 'N_DE_INVITACIONES_CURSADAS']].isna().sum()

N_LICITADORES_PARTICIPANTES    0
N_DE_INVITACIONES_CURSADAS     7
dtype: int64

In [93]:
df['N_DE_INVITACIONES_CURSADAS'] = df['N_DE_INVITACIONES_CURSADAS'].fillna(0).astype('Int64')

In [94]:
df[['N_LICITADORES_PARTICIPANTES', 'N_DE_INVITACIONES_CURSADAS']].isna().sum()

N_LICITADORES_PARTICIPANTES    0
N_DE_INVITACIONES_CURSADAS     0
dtype: int64

In [95]:
df['N_LICITADORES_PARTICIPANTES'].describe()

count       974.0
mean     1.324435
std      0.670536
min           1.0
25%           1.0
50%           1.0
75%           1.0
max           6.0
Name: N_LICITADORES_PARTICIPANTES, dtype: Float64

In [96]:
df['N_DE_REGISTRO_DE_CONTRATO'].is_unique

True

In [97]:
df['N_DE_REGISTRO_DE_CONTRATO'].duplicated().sum()

np.int64(0)

In [98]:
date_columns = ['FECHA_DE_ADJUDICACION', 'FECHA_DE_INSCRIPCION']
for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce',dayfirst=True)

/var/folders/m3/w6hjxzbj5z53fpmr0p_gblfw0000gn/T/ipykernel_319/107939847.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors='coerce',dayfirst=True)
/var/folders/m3/w6hjxzbj5z53fpmr0p_gblfw0000gn/T/ipykernel_319/107939847.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors='coerce',dayfirst=True)

In [99]:
df[date_columns].isna().sum()
df[date_columns].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   FECHA_DE_ADJUDICACION  974 non-null    datetime64[ns]
 1   FECHA_DE_INSCRIPCION   974 non-null    datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 15.3 KB

In [100]:
 (df['FECHA_DE_ADJUDICACION'] > df['FECHA_DE_INSCRIPCION']).sum()

np.int64(0)

In [101]:
df['MES'] = df['FECHA_DE_ADJUDICACION'].dt.to_period('M')

In [102]:
df.head(2)

,N_DE_REGISTRO_DE_CONTRATO,N_DE_EXPEDIENTE,CENTRO_SECCION,ORGANO_DE_CONTRATACION,OBJETO_DEL_CONTRATO,TIPO_DE_CONTRATO,N_DE_INVITACIONES_CURSADAS,INVITADOS_A_PRESENTAR_OFERTA,IMPORTE_LICITACION_IVA_INC,N_LICITADORES_PARTICIPANTES,NIF_ADJUDICATARIO,RAZON_SOCIAL_ADJUDICATARIO,PYME,IMPORTE_ADJUDICACION_IVA_INC,FECHA_DE_ADJUDICACION,PLAZO,FECHA_DE_INSCRIPCION,ORGANISMO_CONTRATANTE,ORGANISMO_PROMOTOR,MES
0,2025015610,511/2025/60303,"VICEALCALDÍA, PORTAVOZ, SEGURID. Y EMERG",DIRECTORA GENERAL DE TRANSPARENCIA Y CALIDAD,Contrato privado para la suscripción a la plat...,Servicios,1,"(B85893493) AENOR CONOCIMIENTO, S.L.U.. PYME: N0",15808.00,1,B85893493,"AENOR CONOCIMIENTO, S.L.U.",NO,15808.00,2025-12-23,12.0,2026-01-02,"ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE...","ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE...",2025-12
1,2025015611,CM25/00076/2,Empresa Municipal de Transportes E.M.T.,DIRECTOR/A GERENTE,"SUMINISTRO DE 103 CHUBASQUEROS, ESPECIALMENTE ...",Suministros,1,(03108110M) SUSANA SANCHEZ MARTÍN. PYME: SI,3601.81,1,03108110M,SUSANA SANCHEZ MARTÍN,SI,3601.81,2025-12-23,3.0,2026-01-05,EMPRESA MUNICIPAL DE TRANSPORTES,EMPRESA MUNICIPAL DE TRANSPORTES,2025-12

In [103]:
kpi_gasto_mes = (df.groupby('MES')['IMPORTE_ADJUDICACION_IVA_INC'].sum().sort_index())
kpi_gasto_mes

MES
2025-07       6283.76
2025-08        886.07
2025-09       8815.78
2025-10      42105.58
2025-11     301871.45
2025-12    1013281.90
2026-01     710853.77
2026-02    2142223.74
2026-03    2605280.29
Freq: M, Name: IMPORTE_ADJUDICACION_IVA_INC, dtype: float64

In [104]:
contratos_mes = (df.groupby('MES')['N_DE_REGISTRO_DE_CONTRATO'].count().sort_index)
contratos_mes

<bound method Series.sort_index of MES
2025-07      1
2025-08      1
2025-09      1
2025-10      3
2025-11     42
2025-12    158
2026-01    122
2026-02    315
2026-03    331
Freq: M, Name: N_DE_REGISTRO_DE_CONTRATO, dtype: int64>

In [105]:
promedio_contratos_mes = (df.groupby('MES')['IMPORTE_ADJUDICACION_IVA_INC'].mean().sort_index())
promedio_contratos_mes

MES
2025-07     6283.760000
2025-08      886.070000
2025-09     8815.780000
2025-10    14035.193333
2025-11     7187.415476
2025-12     6413.176582
2026-01     5826.670246
2026-02     6800.710286
2026-03     7870.937432
Freq: M, Name: IMPORTE_ADJUDICACION_IVA_INC, dtype: float64

In [106]:
df['RAZON_SOCIAL_ADJUDICATARIO'].value_counts().head(20)

RAZON_SOCIAL_ADJUDICATARIO
MERINO Y MERINO PRODUCCIONES, S.L.                                               6
GLOBAL MEDIA Y ENTERTAINMENT , S.A.U.                                            6
Events Branch, S.L.                                                              5
AGR IMAGEN INTEGRAL, S.L.                                                        5
VIVA AQUA SERVICE SPAIN, S.A.                                                    5
GUTHERSA, S.A.                                                                   5
COPYPOC, S.L.                                                                    5
GONZALEZ DE CANALES TEC, S.L.                                                    4
GESTORA DE NUEVOS PROYECTOS CULTURALES, S.L.                                     4
GERRIETS ESPAÑA, S.L.                                                            4
INSTITUCIÓN FERIAL DE MADRID-IFEMA MADRID                                        4
SERINTCOM Servicios Integrales de Comunicación. José Antonio Rodríguez Maurin    4
EVILUX S.L.                                                                      4
PROELIUM SPORT & EQUIPMENT, S.L.                                                 4
PALOMEQUE, S.L.                                                                  4
GESTART MÚSICA PARA TODOS, S.L.                                                  4
SISTEMAS Y SERVICIOS AUDIO, S.L.                                                 4
DISTRIBUCIONES FIGUREX MADRID SL                                                 4
RECIO, S.L.                                                                      3
EURODEL HARPAS, S.L.                                                             3
Name: count, dtype: int64

In [107]:
df['RAZON_SOCIAL_ADJUDICATARIO'].str.contains('SERINTCOM', case=False).sum()

np.int64(4)

In [108]:
df['RAZON_SOCIAL_ADJUDICATARIO'] = (df['RAZON_SOCIAL_ADJUDICATARIO'].str.replace(r'\s+,', ',', regex=True))

In [109]:
df['RAZON_SOCIAL_ADJUDICATARIO'].value_counts().head(20)

RAZON_SOCIAL_ADJUDICATARIO
MERINO Y MERINO PRODUCCIONES, S.L.                                               6
GLOBAL MEDIA Y ENTERTAINMENT, S.A.U.                                             6
Events Branch, S.L.                                                              5
AGR IMAGEN INTEGRAL, S.L.                                                        5
VIVA AQUA SERVICE SPAIN, S.A.                                                    5
GUTHERSA, S.A.                                                                   5
COPYPOC, S.L.                                                                    5
GONZALEZ DE CANALES TEC, S.L.                                                    4
GESTORA DE NUEVOS PROYECTOS CULTURALES, S.L.                                     4
GERRIETS ESPAÑA, S.L.                                                            4
INSTITUCIÓN FERIAL DE MADRID-IFEMA MADRID                                        4
SERINTCOM Servicios Integrales de Comunicación. José Antonio Rodríguez Maurin    4
EVILUX S.L.                                                                      4
PROELIUM SPORT & EQUIPMENT, S.L.                                                 4
PALOMEQUE, S.L.                                                                  4
GESTART MÚSICA PARA TODOS, S.L.                                                  4
SISTEMAS Y SERVICIOS AUDIO, S.L.                                                 4
DISTRIBUCIONES FIGUREX MADRID SL                                                 4
RECIO, S.L.                                                                      3
EURODEL HARPAS, S.L.                                                             3
Name: count, dtype: int64

In [110]:
df['RAZON_SOCIAL_ADJUDICATARIO'].str.upper().str.strip().str.replace(r'\s+', ' ', regex=True)

0                         AENOR CONOCIMIENTO, S.L.U.
1                              SUSANA SANCHEZ MARTÍN
2              ICQD INSTITUTO DE CERTIFICACIÓN, S.L.
3                 ONELEC SUMINISTROS ELECTRICOS S.L.
4                 MARIA TERESA BLASCO MARIN-BORREGON
                           ...
969          UNK INNOVACIÓN Y TELECOMUNICACIÓN, S.L.
970               ASOCIACIÓN MUSICAL CANTA ET AMBULA
971                 DISTRIBUCIONES FIGUREX MADRID SL
972            COSMIKA PRODUCCIONES AUDIOVISUALES SL
973    UNIVERSIDAD NACIONAL DE EDUCACIÓN A DISTANCIA
Name: RAZON_SOCIAL_ADJUDICATARIO, Length: 974, dtype: object

In [112]:
cols_str = [
    'RAZON_SOCIAL_ADJUDICATARIO',
    'TIPO_DE_CONTRATO',
    'ORGANO_DE_CONTRATACION',
    'ORGANISMO_CONTRATANTE',
    'ORGANISMO_PROMOTOR',
    'PYME',
    'CENTRO_SECCION'
]
for col in cols_str:
    df[col] = (
        df[col]
        .str.upper()
        .str.strip()
        .str.replace(r'\s+', ' ', regex=True)
    )

In [113]:
df.head()

,N_DE_REGISTRO_DE_CONTRATO,N_DE_EXPEDIENTE,CENTRO_SECCION,ORGANO_DE_CONTRATACION,OBJETO_DEL_CONTRATO,TIPO_DE_CONTRATO,N_DE_INVITACIONES_CURSADAS,INVITADOS_A_PRESENTAR_OFERTA,IMPORTE_LICITACION_IVA_INC,N_LICITADORES_PARTICIPANTES,NIF_ADJUDICATARIO,RAZON_SOCIAL_ADJUDICATARIO,PYME,IMPORTE_ADJUDICACION_IVA_INC,FECHA_DE_ADJUDICACION,PLAZO,FECHA_DE_INSCRIPCION,ORGANISMO_CONTRATANTE,ORGANISMO_PROMOTOR,MES
0,2025015610,511/2025/60303,"VICEALCALDÍA, PORTAVOZ, SEGURID. Y EMERG",DIRECTORA GENERAL DE TRANSPARENCIA Y CALIDAD,Contrato privado para la suscripción a la plat...,SERVICIOS,1,"(B85893493) AENOR CONOCIMIENTO, S.L.U.. PYME: N0",15808.00,1,B85893493,"AENOR CONOCIMIENTO, S.L.U.",NO,15808.00,2025-12-23,12.00,2026-01-02,"ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE...","ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE...",2025-12
1,2025015611,CM25/00076/2,EMPRESA MUNICIPAL DE TRANSPORTES E.M.T.,DIRECTOR/A GERENTE,"SUMINISTRO DE 103 CHUBASQUEROS, ESPECIALMENTE ...",SUMINISTROS,1,(03108110M) SUSANA SANCHEZ MARTÍN. PYME: SI,3601.81,1,03108110M,SUSANA SANCHEZ MARTÍN,SI,3601.81,2025-12-23,3.00,2026-01-05,EMPRESA MUNICIPAL DE TRANSPORTES,EMPRESA MUNICIPAL DE TRANSPORTES,2025-12
2,2025015653,MER/2025/00468,MERCAMADRID,DIRECTOR/A GENERAL,SERVICIOS DE AUDITORÍA EXTERNA DE CERTIFICACIÓ...,SERVICIOS,1,"(B66084591) ICQD INSTITUTO DE CERTIFICACIÓN, S...",514.25,1,B66084591,"ICQD INSTITUTO DE CERTIFICACIÓN, S.L.",SI,514.25,2025-11-07,6.00,2026-01-05,MERCAMADRID,MERCAMADRID,2025-11
3,2025015655,MER/2025/00442,MERCAMADRID,DIRECTOR/A GENERAL,SUMINISTRO DE CABLE FLEXIBLE DE TENSIÓN,SUMINISTROS,1,(B83128942) ONELEC SUMINISTROS ELECTRICOS S.L....,1452.00,1,B83128942,ONELEC SUMINISTROS ELECTRICOS S.L.,SI,1432.64,2025-11-07,0.23,2026-01-05,MERCAMADRID,MERCAMADRID,2025-11
4,2025015659,PR25-0314.1,"MADRID DESTINO, CULTURA, TURISMO Y NEGOCIO, S.A.",GERENTE DE MATADERO,PR25-0314.1 CONTRATO MENOR DEL SERVICIO DE DI...,SERVICIOS,1,(02549159T) Maria Teresa Blasco Marin-Borregon...,2420.00,1,02549159T,MARIA TERESA BLASCO MARIN-BORREGON,NO,2420.00,2025-12-17,7.40,2026-01-07,MADRID DESTINO,MADRID DESTINO,2025-12

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   N_DE_REGISTRO_DE_CONTRATO     974 non-null    int64
 1   N_DE_EXPEDIENTE               974 non-null    object
 2   CENTRO_SECCION                974 non-null    object
 3   ORGANO_DE_CONTRATACION        974 non-null    object
 4   OBJETO_DEL_CONTRATO           974 non-null    object
 5   TIPO_DE_CONTRATO              974 non-null    object
 6   N_DE_INVITACIONES_CURSADAS    974 non-null    Int64
 7   INVITADOS_A_PRESENTAR_OFERTA  967 non-null    object
 8   IMPORTE_LICITACION_IVA_INC    974 non-null    float64
 9   N_LICITADORES_PARTICIPANTES   974 non-null    Int64
 10  NIF_ADJUDICATARIO             974 non-null    object
 11  RAZON_SOCIAL_ADJUDICATARIO    974 non-null    object
 12  PYME                          974 non-null    object
 13  IMPORTE_ADJUDICACION_IVA_INC  974 non-null    float64
 14  FECHA_DE_ADJUDICACION         974 non-null    datetime64[ns]
 15  PLAZO                         974 non-null    float64
 16  FECHA_DE_INSCRIPCION          974 non-null    datetime64[ns]
 17  ORGANISMO_CONTRATANTE         974 non-null    object
 18  ORGANISMO_PROMOTOR            974 non-null    object
 19  MES                           974 non-null    period[M]
dtypes: Int64(2), datetime64[ns](2), float64(3), int64(1), object(11), period[M](1)
memory usage: 154.2+ KB

In [117]:
df.to_csv('../data/clean/contratos_menores_clean.csv', index=False)