In [3]:
import pandas as pd
df = pd.read_csv('contratos_menores_clean.csv')

In [5]:
df.head()

,N_DE_REGISTRO_DE_CONTRATO,N_DE_EXPEDIENTE,CENTRO_SECCION,ORGANO_DE_CONTRATACION,OBJETO_DEL_CONTRATO,TIPO_DE_CONTRATO,N_DE_INVITACIONES_CURSADAS,INVITADOS_A_PRESENTAR_OFERTA,IMPORTE_LICITACION_IVA_INC,N_LICITADORES_PARTICIPANTES,NIF_ADJUDICATARIO,RAZON_SOCIAL_ADJUDICATARIO,PYME,IMPORTE_ADJUDICACION_IVA_INC,FECHA_DE_ADJUDICACION,PLAZO,FECHA_DE_INSCRIPCION,ORGANISMO_CONTRATANTE,ORGANISMO_PROMOTOR,MES
0,2025015610,511/2025/60303,"VICEALCALDÍA, PORTAVOZ, SEGURID. Y EMERG",DIRECTORA GENERAL DE TRANSPARENCIA Y CALIDAD,Contrato privado para la suscripción a la plat...,SERVICIOS,1,"(B85893493) AENOR CONOCIMIENTO, S.L.U.. PYME: N0",15808.00,1,B85893493,"AENOR CONOCIMIENTO, S.L.U.",NO,15808.00,2025-12-23,12.00,2026-01-02,"ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE...","ÁREA DE GOBIERNO DE VICEALCALDÍA, PORTAVOZ, SE...",2025-12
1,2025015611,CM25/00076/2,EMPRESA MUNICIPAL DE TRANSPORTES E.M.T.,DIRECTOR/A GERENTE,"SUMINISTRO DE 103 CHUBASQUEROS, ESPECIALMENTE ...",SUMINISTROS,1,(03108110M) SUSANA SANCHEZ MARTÍN. PYME: SI,3601.81,1,03108110M,SUSANA SANCHEZ MARTÍN,SI,3601.81,2025-12-23,3.00,2026-01-05,EMPRESA MUNICIPAL DE TRANSPORTES,EMPRESA MUNICIPAL DE TRANSPORTES,2025-12
2,2025015653,MER/2025/00468,MERCAMADRID,DIRECTOR/A GENERAL,SERVICIOS DE AUDITORÍA EXTERNA DE CERTIFICACIÓ...,SERVICIOS,1,"(B66084591) ICQD INSTITUTO DE CERTIFICACIÓN, S...",514.25,1,B66084591,"ICQD INSTITUTO DE CERTIFICACIÓN, S.L.",SI,514.25,2025-11-07,6.00,2026-01-05,MERCAMADRID,MERCAMADRID,2025-11
3,2025015655,MER/2025/00442,MERCAMADRID,DIRECTOR/A GENERAL,SUMINISTRO DE CABLE FLEXIBLE DE TENSIÓN,SUMINISTROS,1,(B83128942) ONELEC SUMINISTROS ELECTRICOS S.L....,1452.00,1,B83128942,ONELEC SUMINISTROS ELECTRICOS S.L.,SI,1432.64,2025-11-07,0.23,2026-01-05,MERCAMADRID,MERCAMADRID,2025-11
4,2025015659,PR25-0314.1,"MADRID DESTINO, CULTURA, TURISMO Y NEGOCIO, S.A.",GERENTE DE MATADERO,PR25-0314.1 CONTRATO MENOR DEL SERVICIO DE DI...,SERVICIOS,1,(02549159T) Maria Teresa Blasco Marin-Borregon...,2420.00,1,02549159T,MARIA TERESA BLASCO MARIN-BORREGON,NO,2420.00,2025-12-17,7.40,2026-01-07,MADRID DESTINO,MADRID DESTINO,2025-12

In [15]:
kpi_gasto_mes = df.groupby('MES', as_index=False)['IMPORTE_ADJUDICACION_IVA_INC'].sum().sort_values('MES')

In [16]:
kpi_gasto_mes

       MES  IMPORTE_ADJUDICACION_IVA_INC
0  2025-07                       6283.76
1  2025-08                        886.07
2  2025-09                       8815.78
3  2025-10                      42105.58
4  2025-11                     301871.45
5  2025-12                    1013281.90
6  2026-01                     710853.77
7  2026-02                    2142223.74
8  2026-03                    2605280.29

In [8]:
df['FECHA_DE_ADJUDICACION'].max()

'2026-03-31'

In [9]:
df['FECHA_DE_ADJUDICACION'].min()

'2025-07-07'

In [12]:
kpi_contratos_mes = df.groupby('MES', as_index=False)['N_DE_REGISTRO_DE_CONTRATO'].count().sort_values('MES')

In [13]:
kpi_contratos_mes

       MES  N_DE_REGISTRO_DE_CONTRATO
0  2025-07                          1
1  2025-08                          1
2  2025-09                          1
3  2025-10                          3
4  2025-11                         42
5  2025-12                        158
6  2026-01                        122
7  2026-02                        315
8  2026-03                        331

In [19]:
kpi_ticket_promedio = df.groupby('MES', as_index=False)['IMPORTE_ADJUDICACION_IVA_INC'].mean().sort_values('MES')

In [20]:
kpi_ticket_promedio

       MES  IMPORTE_ADJUDICACION_IVA_INC
0  2025-07                   6283.760000
1  2025-08                    886.070000
2  2025-09                   8815.780000
3  2025-10                  14035.193333
4  2025-11                   7187.415476
5  2025-12                   6413.176582
6  2026-01                   5826.670246
7  2026-02                   6800.710286
8  2026-03                   7870.937432

In [22]:
kpi_check = kpi_gasto_mes['IMPORTE_ADJUDICACION_IVA_INC'] / kpi_contratos_mes['N_DE_REGISTRO_DE_CONTRATO']
kpi_check

0     6283.760000
1      886.070000
2     8815.780000
3    14035.193333
4     7187.415476
5     6413.176582
6     5826.670246
7     6800.710286
8     7870.937432
dtype: float64

In [24]:
kpi_top_empresas_contratos = (df.groupby('RAZON_SOCIAL_ADJUDICATARIO')
    ['N_DE_REGISTRO_DE_CONTRATO']
    .count()
    .sort_values(ascending=False)
    .head(10)
)                       
kpi_top_empresas_contratos

RAZON_SOCIAL_ADJUDICATARIO
MERINO Y MERINO PRODUCCIONES, S.L.              6
GLOBAL MEDIA Y ENTERTAINMENT, S.A.U.            6
AGR IMAGEN INTEGRAL, S.L.                       5
COPYPOC, S.L.                                   5
EVENTS BRANCH, S.L.                             5
VIVA AQUA SERVICE SPAIN, S.A.                   5
GUTHERSA, S.A.                                  5
GESTART MÚSICA PARA TODOS, S.L.                 4
GERRIETS ESPAÑA, S.L.                           4
GESTORA DE NUEVOS PROYECTOS CULTURALES, S.L.    4
Name: N_DE_REGISTRO_DE_CONTRATO, dtype: int64

In [26]:
kpi_top_empresas_monto = (df.groupby('RAZON_SOCIAL_ADJUDICATARIO')['IMPORTE_ADJUDICACION_IVA_INC']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)
kpi_top_empresas_monto

RAZON_SOCIAL_ADJUDICATARIO
GARTNER ESPAÑA, S.L.                                                             231251.57
MERINO Y MERINO PRODUCCIONES, S.L.                                                71311.17
GLOBAL MEDIA Y ENTERTAINMENT, S.A.U.                                              68098.80
SERINTCOM SERVICIOS INTEGRALES DE COMUNICACIÓN. JOSÉ ANTONIO RODRÍGUEZ MAURIN     66051.48
EVENTOS INFIMA, S.L.                                                              52786.79
INSTITUCIÓN FERIAL DE MADRID-IFEMA MADRID                                         50721.25
TRABAJOS VERTICALES COSTIN, S.L.                                                  48206.40
REIN PROYECTOS SINGULARES, S.L.                                                   42174.99
TEJADOS Y TERRAZAS MADRID, S. L.                                                  38824.67
INSITUFORM TECHNOLOGIES IBERICA, S.A.                                             37478.10
Name: IMPORTE_ADJUDICACION_IVA_INC, dtype: float64

In [28]:
kpi_mediana_mes = (df.groupby('MES', as_index=False)['IMPORTE_ADJUDICACION_IVA_INC']
    .median()
    .sort_values('MES')
)
kpi_mediana_mes

       MES  IMPORTE_ADJUDICACION_IVA_INC
0  2025-07                      6283.760
1  2025-08                       886.070
2  2025-09                      8815.780
3  2025-10                     12100.000
4  2025-11                      3455.305
5  2025-12                      4378.000
6  2026-01                      3630.000
7  2026-02                      3630.000
8  2026-03                      4500.000

In [36]:
kpi_top_organo_contratacion_mes = (df.groupby(['MES', 'ORGANO_DE_CONTRATACION'])['IMPORTE_ADJUDICACION_IVA_INC']
    .sum()
    .reset_index()
    .sort_values(['MES', 'IMPORTE_ADJUDICACION_IVA_INC'], ascending=[True, False])
    .groupby('MES')
    .head(5)
)
kpi_top_organo_contratacion_mes

,MES,ORGANO_DE_CONTRATACION,IMPORTE_ADJUDICACION_IVA_INC
0,2025-07,"DIRECTOR/A DE INFRAESTRUCTURAS, OBRAS Y MANTEN...",6283.76
1,2025-08,"DIRECTOR/A DE INFRAESTRUCTURAS, OBRAS Y MANTEN...",886.07
2,2025-09,GERENTE DE CONDE DUQUE,8815.78
3,2025-10,COORDINADORA DEL DISTRITO DE CARABANCHEL,17908.00
5,2025-10,DIRECTORA GENERAL DE EMPRENDIMIENTO,12100.00
4,2025-10,DIRECTOR/A DE COMUNICACIÓN,12097.58
10,2025-11,"DIRECTOR/A DE INFRAESTRUCTURAS, OBRAS Y MANTEN...",167761.16
11,2025-11,DIRECTOR/A DE PRODUCCIÓN Y COORDINACIÓN TÉCNICA,44667.15
13,2025-11,DIRECTOR/A GENERAL,30741.93
15,2025-11,GERENTE DE TEATRO ESPAÑOL Y NAVES DEL ESPAÑOL ...,24200.00
12,2025-11,"DIRECTOR/A DE RRHH, ORGANIZACIÓN Y FORMACIÓN",15730.00
21,2025-12,DIRECTOR/A DE PRODUCCIÓN Y COORDINACIÓN TÉCNICA,360544.10
20,2025-12,"DIRECTOR/A DE INFRAESTRUCTURAS, OBRAS Y MANTEN...",179334.08
33,2025-12,GERENTE DE TEATRO ESPAÑOL Y NAVES DEL ESPAÑOL ...,126066.20
25,2025-12,DIRECTOR/A GENERAL,110519.51
27,2025-12,DIRECTORA GENERAL DE PATRIMONIO CULTURAL Y PAI...,53236.20
49,2026-01,DIRECTOR/A DE PRODUCCIÓN Y COORDINACIÓN TÉCNICA,97054.54
59,2026-01,GERENTE DE CENTROCENTRO,67452.46
63,2026-01,GERENTE DE TEATRO ESPAÑOL Y NAVES DEL ESPAÑOL ...,65714.22
53,2026-01,DIRECTOR/A GENERAL,57565.64
50,2026-01,DIRECTOR/A DE RELACIONES INSTITUCIONALES,54412.80
100,2026-02,DIRECTOR/A DE PRODUCCIÓN Y COORDINACIÓN TÉCNICA,372246.75
92,2026-02,DIRECTOR GENERAL DE POLICÍA MUNICIPAL,128637.31
126,2026-02,GERENTE MADRID SALUD,127690.07
99,2026-02,"DIRECTOR/A DE INFRAESTRUCTURAS, OBRAS Y MANTEN...",114285.00
72,2026-02,COORDINADOR DEL DISTRITO DE FUENCARRAL-EL PARDO,93406.27
197,2026-03,GERENTE MADRID SALUD,338988.07
154,2026-03,COORDINADORA GENERAL DE LA ALCALDÍA,231251.57
148,2026-03,COORDINADOR GENERAL DE SEGURIDAD Y EMERGENCIAS,185524.50
170,2026-03,DIRECTOR/A DE PRODUCCIÓN Y COORDINACIÓN TÉCNICA,152219.64
196,2026-03,GERENTE INFORMÁTICA DEL AYUNTAMIENTO DE MADRID,93366.42

In [34]:
kpi_tipo_contrato_mes = (df.groupby(['MES', 'TIPO_DE_CONTRATO'])['IMPORTE_ADJUDICACION_IVA_INC']
    .sum()
    .reset_index()
    .sort_values(['MES','IMPORTE_ADJUDICACION_IVA_INC'], ascending=[True, False])
)
kpi_tipo_contrato_mes

        MES TIPO_DE_CONTRATO  IMPORTE_ADJUDICACION_IVA_INC
0   2025-07      SUMINISTROS                       6283.76
1   2025-08      SUMINISTROS                        886.07
2   2025-09        SERVICIOS                       8815.78
3   2025-10        SERVICIOS                      42105.58
5   2025-11        SERVICIOS                     132607.57
4   2025-11            OBRAS                     102785.43
6   2025-11      SUMINISTROS                      66478.45
7   2025-12        SERVICIOS                     742756.88
8   2025-12      SUMINISTROS                     270525.02
10  2026-01        SERVICIOS                     483909.02
11  2026-01      SUMINISTROS                     171853.45
9   2026-01            OBRAS                      55091.30
13  2026-02        SERVICIOS                    1359184.00
14  2026-02      SUMINISTROS                     744215.07
12  2026-02            OBRAS                      38824.67
16  2026-03        SERVICIOS                    1866522.76
17  2026-03      SUMINISTROS                     672127.40
15  2026-03            OBRAS                      66630.13

In [41]:
kpis = {
    'kpi_gasto_mes': kpi_gasto_mes,
    'kpi_contratos_mes': kpi_contratos_mes,
    'kpi_ticket_promedio': kpi_ticket_promedio,
    'kpi_top_empresas_contratos': kpi_top_empresas_contratos,
    'kpi_top_empresas_monto': kpi_top_empresas_monto,
    'kpi_mediana_mes': kpi_mediana_mes,
    'kpi_top_organo_contratacion_mes': kpi_top_organo_contratacion_mes,
    'kpi_tipo_contrato_mes': kpi_tipo_contrato_mes
}
for name, df_kpi in kpis.items():
    df_kpi.reset_index().to_csv(
        f'../output/kpis/{name}.csv',
        index=False
    )

In [40]:
import os
os.getcwd()          # carpeta actual (desde donde corre el notebook)
os.listdir()

['02_analisis.ipynb',
 '.DS_Store',
 'contratos_menores_clean.csv',
 '.ipynb_checkpoints']